source 'https://rubygems.org'

gem 'algorithms'
gem 'connection_pool'
gem 'google-protobuf'
gem 'jwt'
gem 'pg'
gem 'puma'
gem 'rack-test'
gem 'rackup'
gem 'rake'
gem 'require_all'
gem 'rspec'
gem 'rubocop-rake', '~> 0.7.1'
gem 'rubocop-rspec', '~> 3.6'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'tty-command'
