// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: messages.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct AuthResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var response: AuthResponse.OneOf_Response? = nil

  var token: String {
    get {
      if case .token(let v)? = response {return v}
      return String()
    }
    set {response = .token(newValue)}
  }

  var error: String {
    get {
      if case .error(let v)? = response {return v}
      return String()
    }
    set {response = .error(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum OneOf_Response: Equatable, Sendable {
    case token(String)
    case error(String)

  }

  init() {}
}

struct OperationResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var success: Bool = false

  var error: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct VersionResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var response: VersionResponse.OneOf_Response? = nil

  var updateTimeNs: Int64 {
    get {
      if case .updateTimeNs(let v)? = response {return v}
      return 0
    }
    set {response = .updateTimeNs(newValue)}
  }

  var error: String {
    get {
      if case .error(let v)? = response {return v}
      return String()
    }
    set {response = .error(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum OneOf_Response: Equatable, Sendable {
    case updateTimeNs(Int64)
    case error(String)

  }

  init() {}
}

struct Name: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var name: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct SortName: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var name: String = String()

  var sortName: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Track: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var id: String {
    get {_storage._id}
    set {_uniqueStorage()._id = newValue}
  }

  var name: String {
    get {_storage._name}
    set {_uniqueStorage()._name = newValue}
  }

  var sortName: String {
    get {_storage._sortName}
    set {_uniqueStorage()._sortName = newValue}
  }

  var artistID: UInt64 {
    get {_storage._artistID}
    set {_uniqueStorage()._artistID = newValue}
  }

  var albumArtistID: UInt64 {
    get {_storage._albumArtistID}
    set {_uniqueStorage()._albumArtistID = newValue}
  }

  var albumID: UInt64 {
    get {_storage._albumID}
    set {_uniqueStorage()._albumID = newValue}
  }

  var genreID: UInt64 {
    get {_storage._genreID}
    set {_uniqueStorage()._genreID = newValue}
  }

  var year: UInt32 {
    get {_storage._year}
    set {_uniqueStorage()._year = newValue}
  }

  var duration: Float {
    get {_storage._duration}
    set {_uniqueStorage()._duration = newValue}
  }

  var start: Float {
    get {_storage._start}
    set {_uniqueStorage()._start = newValue}
  }

  var finish: Float {
    get {_storage._finish}
    set {_uniqueStorage()._finish = newValue}
  }

  var trackNumber: UInt32 {
    get {_storage._trackNumber}
    set {_uniqueStorage()._trackNumber = newValue}
  }

  var discNumber: UInt32 {
    get {_storage._discNumber}
    set {_uniqueStorage()._discNumber = newValue}
  }

  var playCount: UInt64 {
    get {_storage._playCount}
    set {_uniqueStorage()._playCount = newValue}
  }

  var rating: Int32 {
    get {_storage._rating}
    set {_uniqueStorage()._rating = newValue}
  }

  /// skip 16-18
  var artworkFilename: String {
    get {_storage._artworkFilename}
    set {_uniqueStorage()._artworkFilename = newValue}
  }

  var playlistIds: [String] {
    get {_storage._playlistIds}
    set {_uniqueStorage()._playlistIds = newValue}
  }

  var musicFilename: String {
    get {_storage._musicFilename}
    set {_uniqueStorage()._musicFilename = newValue}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

struct Playlist: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var id: String = String()

  var name: String = String()

  var parentID: String = String()

  var isLibrary: Bool = false

  var trackIds: [String] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Library: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var genres: Dictionary<UInt64,Name> = [:]

  var artists: Dictionary<UInt64,SortName> = [:]

  var albums: Dictionary<UInt64,SortName> = [:]

  var tracks: [Track] = []

  var playlists: [Playlist] = []

  var trackUserChanges: Bool = false

  var totalFileSize: UInt64 = 0

  var updateTimeNs: Int64 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct LibraryResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var response: LibraryResponse.OneOf_Response? = nil

  var library: Library {
    get {
      if case .library(let v)? = response {return v}
      return Library()
    }
    set {response = .library(newValue)}
  }

  var error: String {
    get {
      if case .error(let v)? = response {return v}
      return String()
    }
    set {response = .error(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum OneOf_Response: Equatable, Sendable {
    case library(Library)
    case error(String)

  }

  init() {}
}

/// trims the library to just these playlists (for the watch)
struct LibraryRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var playlistIds: [String] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct BundleRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var type: BundleRequest.TypeEnum = .music

  var filenames: [String] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum TypeEnum: SwiftProtobuf.Enum, Swift.CaseIterable {
    typealias RawValue = Int
    case music // = 0
    case artwork // = 1
    case UNRECOGNIZED(Int)

    init() {
      self = .music
    }

    init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .music
      case 1: self = .artwork
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    var rawValue: Int {
      switch self {
      case .music: return 0
      case .artwork: return 1
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    static let allCases: [BundleRequest.TypeEnum] = [
      .music,
      .artwork,
    ]

  }

  init() {}
}

struct BundleResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var response: BundleResponse.OneOf_Response? = nil

  var id: String {
    get {
      if case .id(let v)? = response {return v}
      return String()
    }
    set {response = .id(newValue)}
  }

  var error: String {
    get {
      if case .error(let v)? = response {return v}
      return String()
    }
    set {response = .error(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum OneOf_Response: Equatable, Sendable {
    case id(String)
    case error(String)

  }

  init() {}
}

/// edited track fields; only fields that are present are updated, and a
/// present but empty album/albumArtist/artwork clears the value
struct TrackUpdate: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var name: String {
    get {_name ?? String()}
    set {_name = newValue}
  }
  /// Returns true if `name` has been explicitly set.
  var hasName: Bool {self._name != nil}
  /// Clears the value of `name`. Subsequent reads from it will return its default value.
  mutating func clearName() {self._name = nil}

  var artist: String {
    get {_artist ?? String()}
    set {_artist = newValue}
  }
  /// Returns true if `artist` has been explicitly set.
  var hasArtist: Bool {self._artist != nil}
  /// Clears the value of `artist`. Subsequent reads from it will return its default value.
  mutating func clearArtist() {self._artist = nil}

  var album: String {
    get {_album ?? String()}
    set {_album = newValue}
  }
  /// Returns true if `album` has been explicitly set.
  var hasAlbum: Bool {self._album != nil}
  /// Clears the value of `album`. Subsequent reads from it will return its default value.
  mutating func clearAlbum() {self._album = nil}

  var albumArtist: String {
    get {_albumArtist ?? String()}
    set {_albumArtist = newValue}
  }
  /// Returns true if `albumArtist` has been explicitly set.
  var hasAlbumArtist: Bool {self._albumArtist != nil}
  /// Clears the value of `albumArtist`. Subsequent reads from it will return its default value.
  mutating func clearAlbumArtist() {self._albumArtist = nil}

  var genre: String {
    get {_genre ?? String()}
    set {_genre = newValue}
  }
  /// Returns true if `genre` has been explicitly set.
  var hasGenre: Bool {self._genre != nil}
  /// Clears the value of `genre`. Subsequent reads from it will return its default value.
  mutating func clearGenre() {self._genre = nil}

  var year: Int32 {
    get {_year ?? 0}
    set {_year = newValue}
  }
  /// Returns true if `year` has been explicitly set.
  var hasYear: Bool {self._year != nil}
  /// Clears the value of `year`. Subsequent reads from it will return its default value.
  mutating func clearYear() {self._year = nil}

  var start: Double {
    get {_start ?? 0}
    set {_start = newValue}
  }
  /// Returns true if `start` has been explicitly set.
  var hasStart: Bool {self._start != nil}
  /// Clears the value of `start`. Subsequent reads from it will return its default value.
  mutating func clearStart() {self._start = nil}

  var finish: Double {
    get {_finish ?? 0}
    set {_finish = newValue}
  }
  /// Returns true if `finish` has been explicitly set.
  var hasFinish: Bool {self._finish != nil}
  /// Clears the value of `finish`. Subsequent reads from it will return its default value.
  mutating func clearFinish() {self._finish = nil}

  var artwork: String {
    get {_artwork ?? String()}
    set {_artwork = newValue}
  }
  /// Returns true if `artwork` has been explicitly set.
  var hasArtwork: Bool {self._artwork != nil}
  /// Clears the value of `artwork`. Subsequent reads from it will return its default value.
  mutating func clearArtwork() {self._artwork = nil}

  var rating: Int32 {
    get {_rating ?? 0}
    set {_rating = newValue}
  }
  /// Returns true if `rating` has been explicitly set.
  var hasRating: Bool {self._rating != nil}
  /// Clears the value of `rating`. Subsequent reads from it will return its default value.
  mutating func clearRating() {self._rating = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _name: String? = nil
  fileprivate var _artist: String? = nil
  fileprivate var _album: String? = nil
  fileprivate var _albumArtist: String? = nil
  fileprivate var _genre: String? = nil
  fileprivate var _year: Int32? = nil
  fileprivate var _start: Double? = nil
  fileprivate var _finish: Double? = nil
  fileprivate var _artwork: String? = nil
  fileprivate var _rating: Int32? = nil
}

struct IncrementUpdate: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var trackID: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct IntUpdate: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var trackID: String = String()

  var value: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct FloatUpdate: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var trackID: String = String()

  var value: Float = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct StringUpdate: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var trackID: String = String()

  var value: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Updates: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var plays: [IncrementUpdate] = []

  var ratings: [IntUpdate] = []

  var names: [StringUpdate] = []

  var artists: [StringUpdate] = []

  var albums: [StringUpdate] = []

  var albumArtists: [StringUpdate] = []

  var genres: [StringUpdate] = []

  var years: [IntUpdate] = []

  var starts: [FloatUpdate] = []

  var finishes: [FloatUpdate] = []

  var artworks: [StringUpdate] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct UpdatesResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var response: UpdatesResponse.OneOf_Response? = nil

  var updates: Updates {
    get {
      if case .updates(let v)? = response {return v}
      return Updates()
    }
    set {response = .updates(newValue)}
  }

  var error: String {
    get {
      if case .error(let v)? = response {return v}
      return String()
    }
    set {response = .error(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum OneOf_Response: Equatable, Sendable {
    case updates(Updates)
    case error(String)

  }

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension AuthResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "AuthResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}token\0\u{1}error\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.response != nil {try decoder.handleConflictingOneOf()}
          self.response = .token(v)
        }
      }()
      case 2: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.response != nil {try decoder.handleConflictingOneOf()}
          self.response = .error(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.response {
    case .token?: try {
      guard case .token(let v)? = self.response else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    }()
    case .error?: try {
      guard case .error(let v)? = self.response else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: AuthResponse, rhs: AuthResponse) -> Bool {
    if lhs.response != rhs.response {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension OperationResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "OperationResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}success\0\u{1}error\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.success) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.error) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.success != false {
      try visitor.visitSingularBoolField(value: self.success, fieldNumber: 1)
    }
    if !self.error.isEmpty {
      try visitor.visitSingularStringField(value: self.error, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: OperationResponse, rhs: OperationResponse) -> Bool {
    if lhs.success != rhs.success {return false}
    if lhs.error != rhs.error {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VersionResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "VersionResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}updateTimeNs\0\u{1}error\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Int64?
        try decoder.decodeSingularInt64Field(value: &v)
        if let v = v {
          if self.response != nil {try decoder.handleConflictingOneOf()}
          self.response = .updateTimeNs(v)
        }
      }()
      case 2: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.response != nil {try decoder.handleConflictingOneOf()}
          self.response = .error(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.response {
    case .updateTimeNs?: try {
      guard case .updateTimeNs(let v)? = self.response else { preconditionFailure() }
      try visitor.visitSingularInt64Field(value: v, fieldNumber: 1)
    }()
    case .error?: try {
      guard case .error(let v)? = self.response else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: VersionResponse, rhs: VersionResponse) -> Bool {
    if lhs.response != rhs.response {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Name: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "Name"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\u{2}name\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 2: try { try decoder.decodeSingularStringField(value: &self.name) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Name, rhs: Name) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension SortName: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "SortName"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\u{2}name\0\u{1}sortName\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 2: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.sortName) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 2)
    }
    if !self.sortName.isEmpty {
      try visitor.visitSingularStringField(value: self.sortName, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: SortName, rhs: SortName) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.sortName != rhs.sortName {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Track: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "Track"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{1}name\0\u{1}sortName\0\u{1}artistId\0\u{1}albumArtistId\0\u{1}albumId\0\u{1}genreId\0\u{1}year\0\u{1}duration\0\u{1}start\0\u{1}finish\0\u{1}trackNumber\0\u{1}discNumber\0\u{1}playCount\0\u{1}rating\0\u{2}\u{4}artworkFilename\0\u{1}playlistIds\0\u{1}musicFilename\0")

  fileprivate class _StorageClass {
    var _id: String = String()
    var _name: String = String()
    var _sortName: String = String()
    var _artistID: UInt64 = 0
    var _albumArtistID: UInt64 = 0
    var _albumID: UInt64 = 0
    var _genreID: UInt64 = 0
    var _year: UInt32 = 0
    var _duration: Float = 0
    var _start: Float = 0
    var _finish: Float = 0
    var _trackNumber: UInt32 = 0
    var _discNumber: UInt32 = 0
    var _playCount: UInt64 = 0
    var _rating: Int32 = 0
    var _artworkFilename: String = String()
    var _playlistIds: [String] = []
    var _musicFilename: String = String()

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _id = source._id
      _name = source._name
      _sortName = source._sortName
      _artistID = source._artistID
      _albumArtistID = source._albumArtistID
      _albumID = source._albumID
      _genreID = source._genreID
      _year = source._year
      _duration = source._duration
      _start = source._start
      _finish = source._finish
      _trackNumber = source._trackNumber
      _discNumber = source._discNumber
      _playCount = source._playCount
      _rating = source._rating
      _artworkFilename = source._artworkFilename
      _playlistIds = source._playlistIds
      _musicFilename = source._musicFilename
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularStringField(value: &_storage._id) }()
        case 2: try { try decoder.decodeSingularStringField(value: &_storage._name) }()
        case 3: try { try decoder.decodeSingularStringField(value: &_storage._sortName) }()
        case 4: try { try decoder.decodeSingularUInt64Field(value: &_storage._artistID) }()
        case 5: try { try decoder.decodeSingularUInt64Field(value: &_storage._albumArtistID) }()
        case 6: try { try decoder.decodeSingularUInt64Field(value: &_storage._albumID) }()
        case 7: try { try decoder.decodeSingularUInt64Field(value: &_storage._genreID) }()
        case 8: try { try decoder.decodeSingularUInt32Field(value: &_storage._year) }()
        case 9: try { try decoder.decodeSingularFloatField(value: &_storage._duration) }()
        case 10: try { try decoder.decodeSingularFloatField(value: &_storage._start) }()
        case 11: try { try decoder.decodeSingularFloatField(value: &_storage._finish) }()
        case 12: try { try decoder.decodeSingularUInt32Field(value: &_storage._trackNumber) }()
        case 13: try { try decoder.decodeSingularUInt32Field(value: &_storage._discNumber) }()
        case 14: try { try decoder.decodeSingularUInt64Field(value: &_storage._playCount) }()
        case 15: try { try decoder.decodeSingularInt32Field(value: &_storage._rating) }()
        case 19: try { try decoder.decodeSingularStringField(value: &_storage._artworkFilename) }()
        case 20: try { try decoder.decodeRepeatedStringField(value: &_storage._playlistIds) }()
        case 21: try { try decoder.decodeSingularStringField(value: &_storage._musicFilename) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if !_storage._id.isEmpty {
        try visitor.visitSingularStringField(value: _storage._id, fieldNumber: 1)
      }
      if !_storage._name.isEmpty {
        try visitor.visitSingularStringField(value: _storage._name, fieldNumber: 2)
      }
      if !_storage._sortName.isEmpty {
        try visitor.visitSingularStringField(value: _storage._sortName, fieldNumber: 3)
      }
      if _storage._artistID != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._artistID, fieldNumber: 4)
      }
      if _storage._albumArtistID != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._albumArtistID, fieldNumber: 5)
      }
      if _storage._albumID != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._albumID, fieldNumber: 6)
      }
      if _storage._genreID != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._genreID, fieldNumber: 7)
      }
      if _storage._year != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._year, fieldNumber: 8)
      }
      if _storage._duration.bitPattern != 0 {
        try visitor.visitSingularFloatField(value: _storage._duration, fieldNumber: 9)
      }
      if _storage._start.bitPattern != 0 {
        try visitor.visitSingularFloatField(value: _storage._start, fieldNumber: 10)
      }
      if _storage._finish.bitPattern != 0 {
        try visitor.visitSingularFloatField(value: _storage._finish, fieldNumber: 11)
      }
      if _storage._trackNumber != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._trackNumber, fieldNumber: 12)
      }
      if _storage._discNumber != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._discNumber, fieldNumber: 13)
      }
      if _storage._playCount != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._playCount, fieldNumber: 14)
      }
      if _storage._rating != 0 {
        try visitor.visitSingularInt32Field(value: _storage._rating, fieldNumber: 15)
      }
      if !_storage._artworkFilename.isEmpty {
        try visitor.visitSingularStringField(value: _storage._artworkFilename, fieldNumber: 19)
      }
      if !_storage._playlistIds.isEmpty {
        try visitor.visitRepeatedStringField(value: _storage._playlistIds, fieldNumber: 20)
      }
      if !_storage._musicFilename.isEmpty {
        try visitor.visitSingularStringField(value: _storage._musicFilename, fieldNumber: 21)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Track, rhs: Track) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._id != rhs_storage._id {return false}
        if _storage._name != rhs_storage._name {return false}
        if _storage._sortName != rhs_storage._sortName {return false}
        if _storage._artistID != rhs_storage._artistID {return false}
        if _storage._albumArtistID != rhs_storage._albumArtistID {return false}
        if _storage._albumID != rhs_storage._albumID {return false}
        if _storage._genreID != rhs_storage._genreID {return false}
        if _storage._year != rhs_storage._year {return false}
        if _storage._duration != rhs_storage._duration {return false}
        if _storage._start != rhs_storage._start {return false}
        if _storage._finish != rhs_storage._finish {return false}
        if _storage._trackNumber != rhs_storage._trackNumber {return false}
        if _storage._discNumber != rhs_storage._discNumber {return false}
        if _storage._playCount != rhs_storage._playCount {return false}
        if _storage._rating != rhs_storage._rating {return false}
        if _storage._artworkFilename != rhs_storage._artworkFilename {return false}
        if _storage._playlistIds != rhs_storage._playlistIds {return false}
        if _storage._musicFilename != rhs_storage._musicFilename {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Playlist: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "Playlist"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{1}name\0\u{1}parentId\0\u{1}isLibrary\0\u{1}trackIds\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.parentID) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self.isLibrary) }()
      case 5: try { try decoder.decodeRepeatedStringField(value: &self.trackIds) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 2)
    }
    if !self.parentID.isEmpty {
      try visitor.visitSingularStringField(value: self.parentID, fieldNumber: 3)
    }
    if self.isLibrary != false {
      try visitor.visitSingularBoolField(value: self.isLibrary, fieldNumber: 4)
    }
    if !self.trackIds.isEmpty {
      try visitor.visitRepeatedStringField(value: self.trackIds, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Playlist, rhs: Playlist) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.name != rhs.name {return false}
    if lhs.parentID != rhs.parentID {return false}
    if lhs.isLibrary != rhs.isLibrary {return false}
    if lhs.trackIds != rhs.trackIds {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Library: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "Library"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}genres\0\u{1}artists\0\u{1}albums\0\u{1}tracks\0\u{1}playlists\0\u{1}trackUserChanges\0\u{1}totalFileSize\0\u{1}updateTimeNs\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufUInt64,Name>.self, value: &self.genres) }()
      case 2: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufUInt64,SortName>.self, value: &self.artists) }()
      case 3: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufUInt64,SortName>.self, value: &self.albums) }()
      case 4: try { try decoder.decodeRepeatedMessageField(value: &self.tracks) }()
      case 5: try { try decoder.decodeRepeatedMessageField(value: &self.playlists) }()
      case 6: try { try decoder.decodeSingularBoolField(value: &self.trackUserChanges) }()
      case 7: try { try decoder.decodeSingularUInt64Field(value: &self.totalFileSize) }()
      case 8: try { try decoder.decodeSingularInt64Field(value: &self.updateTimeNs) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.genres.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufUInt64,Name>.self, value: self.genres, fieldNumber: 1)
    }
    if !self.artists.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufUInt64,SortName>.self, value: self.artists, fieldNumber: 2)
    }
    if !self.albums.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufUInt64,SortName>.self, value: self.albums, fieldNumber: 3)
    }
    if !self.tracks.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.tracks, fieldNumber: 4)
    }
    if !self.playlists.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.playlists, fieldNumber: 5)
    }
    if self.trackUserChanges != false {
      try visitor.visitSingularBoolField(value: self.trackUserChanges, fieldNumber: 6)
    }
    if self.totalFileSize != 0 {
      try visitor.visitSingularUInt64Field(value: self.totalFileSize, fieldNumber: 7)
    }
    if self.updateTimeNs != 0 {
      try visitor.visitSingularInt64Field(value: self.updateTimeNs, fieldNumber: 8)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Library, rhs: Library) -> Bool {
    if lhs.genres != rhs.genres {return false}
    if lhs.artists != rhs.artists {return false}
    if lhs.albums != rhs.albums {return false}
    if lhs.tracks != rhs.tracks {return false}
    if lhs.playlists != rhs.playlists {return false}
    if lhs.trackUserChanges != rhs.trackUserChanges {return false}
    if lhs.totalFileSize != rhs.totalFileSize {return false}
    if lhs.updateTimeNs != rhs.updateTimeNs {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension LibraryResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "LibraryResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}library\0\u{1}error\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Library?
        var hadOneofValue = false
        if let current = self.response {
          hadOneofValue = true
          if case .library(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.response = .library(v)
        }
      }()
      case 2: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.response != nil {try decoder.handleConflictingOneOf()}
          self.response = .error(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.response {
    case .library?: try {
      guard case .library(let v)? = self.response else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .error?: try {
      guard case .error(let v)? = self.response else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: LibraryResponse, rhs: LibraryResponse) -> Bool {
    if lhs.response != rhs.response {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension LibraryRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "LibraryRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}playlistIds\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedStringField(value: &self.playlistIds) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.playlistIds.isEmpty {
      try visitor.visitRepeatedStringField(value: self.playlistIds, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: LibraryRequest, rhs: LibraryRequest) -> Bool {
    if lhs.playlistIds != rhs.playlistIds {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension BundleRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "BundleRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}type\0\u{1}filenames\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.type) }()
      case 2: try { try decoder.decodeRepeatedStringField(value: &self.filenames) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.type != .music {
      try visitor.visitSingularEnumField(value: self.type, fieldNumber: 1)
    }
    if !self.filenames.isEmpty {
      try visitor.visitRepeatedStringField(value: self.filenames, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: BundleRequest, rhs: BundleRequest) -> Bool {
    if lhs.type != rhs.type {return false}
    if lhs.filenames != rhs.filenames {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension BundleRequest.TypeEnum: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0MUSIC\0\u{1}ARTWORK\0")
}

extension BundleResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "BundleResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{1}error\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.response != nil {try decoder.handleConflictingOneOf()}
          self.response = .id(v)
        }
      }()
      case 2: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.response != nil {try decoder.handleConflictingOneOf()}
          self.response = .error(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.response {
    case .id?: try {
      guard case .id(let v)? = self.response else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    }()
    case .error?: try {
      guard case .error(let v)? = self.response else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: BundleResponse, rhs: BundleResponse) -> Bool {
    if lhs.response != rhs.response {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension TrackUpdate: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "TrackUpdate"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}artist\0\u{1}album\0\u{1}albumArtist\0\u{1}genre\0\u{1}year\0\u{1}start\0\u{1}finish\0\u{1}artwork\0\u{1}rating\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._name) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._artist) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._album) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._albumArtist) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self._genre) }()
      case 6: try { try decoder.decodeSingularInt32Field(value: &self._year) }()
      case 7: try { try decoder.decodeSingularDoubleField(value: &self._start) }()
      case 8: try { try decoder.decodeSingularDoubleField(value: &self._finish) }()
      case 9: try { try decoder.decodeSingularStringField(value: &self._artwork) }()
      case 10: try { try decoder.decodeSingularInt32Field(value: &self._rating) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._name {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._artist {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._album {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._albumArtist {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._genre {
      try visitor.visitSingularStringField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._year {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._start {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 7)
    } }()
    try { if let v = self._finish {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 8)
    } }()
    try { if let v = self._artwork {
      try visitor.visitSingularStringField(value: v, fieldNumber: 9)
    } }()
    try { if let v = self._rating {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 10)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: TrackUpdate, rhs: TrackUpdate) -> Bool {
    if lhs._name != rhs._name {return false}
    if lhs._artist != rhs._artist {return false}
    if lhs._album != rhs._album {return false}
    if lhs._albumArtist != rhs._albumArtist {return false}
    if lhs._genre != rhs._genre {return false}
    if lhs._year != rhs._year {return false}
    if lhs._start != rhs._start {return false}
    if lhs._finish != rhs._finish {return false}
    if lhs._artwork != rhs._artwork {return false}
    if lhs._rating != rhs._rating {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension IncrementUpdate: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "IncrementUpdate"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}trackId\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.trackID) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.trackID.isEmpty {
      try visitor.visitSingularStringField(value: self.trackID, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: IncrementUpdate, rhs: IncrementUpdate) -> Bool {
    if lhs.trackID != rhs.trackID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension IntUpdate: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "IntUpdate"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}trackId\0\u{1}value\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.trackID) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.value) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.trackID.isEmpty {
      try visitor.visitSingularStringField(value: self.trackID, fieldNumber: 1)
    }
    if self.value != 0 {
      try visitor.visitSingularInt32Field(value: self.value, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: IntUpdate, rhs: IntUpdate) -> Bool {
    if lhs.trackID != rhs.trackID {return false}
    if lhs.value != rhs.value {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension FloatUpdate: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "FloatUpdate"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}trackId\0\u{1}value\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.trackID) }()
      case 2: try { try decoder.decodeSingularFloatField(value: &self.value) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.trackID.isEmpty {
      try visitor.visitSingularStringField(value: self.trackID, fieldNumber: 1)
    }
    if self.value.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.value, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: FloatUpdate, rhs: FloatUpdate) -> Bool {
    if lhs.trackID != rhs.trackID {return false}
    if lhs.value != rhs.value {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension StringUpdate: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "StringUpdate"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}trackId\0\u{1}value\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.trackID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.value) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.trackID.isEmpty {
      try visitor.visitSingularStringField(value: self.trackID, fieldNumber: 1)
    }
    if !self.value.isEmpty {
      try visitor.visitSingularStringField(value: self.value, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: StringUpdate, rhs: StringUpdate) -> Bool {
    if lhs.trackID != rhs.trackID {return false}
    if lhs.value != rhs.value {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Updates: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "Updates"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}plays\0\u{1}ratings\0\u{1}names\0\u{1}artists\0\u{1}albums\0\u{1}albumArtists\0\u{1}genres\0\u{1}years\0\u{1}starts\0\u{1}finishes\0\u{1}artworks\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.plays) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.ratings) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.names) }()
      case 4: try { try decoder.decodeRepeatedMessageField(value: &self.artists) }()
      case 5: try { try decoder.decodeRepeatedMessageField(value: &self.albums) }()
      case 6: try { try decoder.decodeRepeatedMessageField(value: &self.albumArtists) }()
      case 7: try { try decoder.decodeRepeatedMessageField(value: &self.genres) }()
      case 8: try { try decoder.decodeRepeatedMessageField(value: &self.years) }()
      case 9: try { try decoder.decodeRepeatedMessageField(value: &self.starts) }()
      case 10: try { try decoder.decodeRepeatedMessageField(value: &self.finishes) }()
      case 11: try { try decoder.decodeRepeatedMessageField(value: &self.artworks) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.plays.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.plays, fieldNumber: 1)
    }
    if !self.ratings.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.ratings, fieldNumber: 2)
    }
    if !self.names.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.names, fieldNumber: 3)
    }
    if !self.artists.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.artists, fieldNumber: 4)
    }
    if !self.albums.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.albums, fieldNumber: 5)
    }
    if !self.albumArtists.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.albumArtists, fieldNumber: 6)
    }
    if !self.genres.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.genres, fieldNumber: 7)
    }
    if !self.years.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.years, fieldNumber: 8)
    }
    if !self.starts.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.starts, fieldNumber: 9)
    }
    if !self.finishes.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.finishes, fieldNumber: 10)
    }
    if !self.artworks.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.artworks, fieldNumber: 11)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Updates, rhs: Updates) -> Bool {
    if lhs.plays != rhs.plays {return false}
    if lhs.ratings != rhs.ratings {return false}
    if lhs.names != rhs.names {return false}
    if lhs.artists != rhs.artists {return false}
    if lhs.albums != rhs.albums {return false}
    if lhs.albumArtists != rhs.albumArtists {return false}
    if lhs.genres != rhs.genres {return false}
    if lhs.years != rhs.years {return false}
    if lhs.starts != rhs.starts {return false}
    if lhs.finishes != rhs.finishes {return false}
    if lhs.artworks != rhs.artworks {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension UpdatesResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "UpdatesResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}updates\0\u{1}error\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Updates?
        var hadOneofValue = false
        if let current = self.response {
          hadOneofValue = true
          if case .updates(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.response = .updates(v)
        }
      }()
      case 2: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.response != nil {try decoder.handleConflictingOneOf()}
          self.response = .error(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.response {
    case .updates?: try {
      guard case .updates(let v)? = self.response else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .error?: try {
      guard case .error(let v)? = self.response else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: UpdatesResponse, rhs: UpdatesResponse) -> Bool {
    if lhs.response != rhs.response {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
