export const ROW_HEIGHT = 31;
export const HEADER_HEIGHT = 31;
export const CELL_HORIZONTAL_PADDING_SIDE = 8;
export const CELL_HORIZONTAL_PADDING_TOTAL = CELL_HORIZONTAL_PADDING_SIDE * 2;
export const DEFAULT_COLUMN_WIDTH = 150;
